import { act, cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import type { AudioRecorder, RecordedAudio } from "../audio/recorder";
import { ConversationStage } from "../components/ConversationStage";
import { TalkControl } from "../components/TalkControl";
import type { TutorTurn, TutorTurnRequest } from "../types/tutor";
import { useTutorConversation } from "./useTutorConversation";

function createRecording(index: number): RecordedAudio {
  const blob = new Blob([`audio-${index}`], { type: "audio/webm" });
  return {
    blob,
    playbackUrl: `blob:recording-${index}`,
    durationMs: 1200,
    mimeType: "audio/webm",
    sizeBytes: blob.size,
  };
}

function createRecorder(): AudioRecorder {
  let recordingIndex = 0;
  return {
    start: vi.fn().mockResolvedValue(undefined),
    stop: vi.fn().mockImplementation(async () => createRecording(++recordingIndex)),
    cancel: vi.fn(),
    dispose: vi.fn(),
  };
}

function turn(reply: string): TutorTurn {
  return {
    reply,
    corrections: [
      {
        original: "since many years",
        correction: "for many years",
        explanation: "Use for with a duration.",
        category: "grammar",
        severity: "important",
      },
    ],
    betterExpressions: [],
  };
}

function ConversationHarness({
  now,
  recorder,
  respond,
  transcribe,
}: {
  now?: () => number;
  recorder: AudioRecorder;
  respond: (request: TutorTurnRequest) => Promise<TutorTurn>;
  transcribe: () => Promise<{ text: string }>;
}) {
  const conversation = useTutorConversation({
    enabled: true,
    recorder,
    respond,
    transcribe,
    now,
  });

  return (
    <>
      <ConversationStage
        exchanges={conversation.exchanges}
        state={conversation.state}
        thinking={conversation.thinking}
      />
      <TalkControl
        disabled={conversation.thinking}
        onEnd={(owner) => void conversation.end(owner)}
        onStart={(owner) => void conversation.begin(owner)}
        state={conversation.state}
        thinking={conversation.thinking}
      />
    </>
  );
}

async function recordOneTurn() {
  fireEvent.keyDown(window, { code: "Space" });
  await screen.findByText("Listening");
  fireEvent.keyUp(window, { code: "Space" });
}

afterEach(() => {
  cleanup();
  vi.restoreAllMocks();
});

describe("useTutorConversation", () => {
  it("shows measured response time and Ollama output throughput", async () => {
    const recorder = createRecorder();
    let clock = 1_000;
    const respond = vi.fn().mockImplementation(async () => {
      clock = 13_540;
      return {
        ...turn("I'm doing well. How about you?"),
        performance: {
          outputTokens: 104,
          tokensPerSecond: 27.506,
        },
      };
    });

    render(
      <ConversationHarness
        now={() => clock}
        recorder={recorder}
        respond={respond}
        transcribe={async () => ({ text: "How are you today?" })}
      />,
    );

    await recordOneTurn();

    expect(await screen.findByText("I'm doing well. How about you?")).toBeInTheDocument();
    expect(screen.getByText("Responded in")).toHaveTextContent(
      "Responded in 12.5 s · 27.5 tok/s",
    );
    expect(screen.getByLabelText("27.5 output tokens per second")).toHaveAttribute(
      "title",
      "104 output tokens generated by Ollama",
    );
  });

  it("shows thinking, stores hidden corrections, and sends prior context on turn two", async () => {
    const recorder = createRecorder();
    const transcribe = vi
      .fn()
      .mockResolvedValueOnce({ text: "I have used React since many years." })
      .mockResolvedValueOnce({ text: "Now I am learning Rust." });
    let resolveFirst: ((value: TutorTurn) => void) | undefined;
    const respond = vi
      .fn<(request: TutorTurnRequest) => Promise<TutorTurn>>()
      .mockImplementationOnce(
        () =>
          new Promise((resolve) => {
            resolveFirst = resolve;
          }),
      )
      .mockResolvedValueOnce(turn("Rust is a useful complement. What are you building?"));

    render(
      <ConversationHarness
        recorder={recorder}
        respond={respond}
        transcribe={transcribe}
      />,
    );

    await recordOneTurn();

    expect(await screen.findByText("Tutor is thinking locally")).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Thinking…" })).toBeDisabled();
    expect(respond).toHaveBeenCalledWith({
      transcript: "I have used React since many years.",
      history: [],
    });

    await act(async () => {
      resolveFirst?.(turn("That is substantial React experience. What backend area interests you?"));
    });

    expect(
      await screen.findByText(
        "That is substantial React experience. What backend area interests you?",
      ),
    ).toBeInTheDocument();
    expect(screen.queryByText("for many years")).not.toBeInTheDocument();
    expect(screen.getByRole("button", { name: /hold to talk/i })).toBeEnabled();

    await recordOneTurn();
    await waitFor(() => expect(respond).toHaveBeenCalledTimes(2));
    expect(respond).toHaveBeenLastCalledWith({
      transcript: "Now I am learning Rust.",
      history: [
        { role: "user", content: "I have used React since many years." },
        {
          role: "assistant",
          content:
            "That is substantial React experience. What backend area interests you?",
        },
      ],
    });
    expect(
      await screen.findByText("Rust is a useful complement. What are you building?"),
    ).toBeInTheDocument();
  });

  it("keeps the transcript, exposes tutor errors, and becomes recoverable", async () => {
    const recorder = createRecorder();
    const respond = vi.fn().mockRejectedValue({
      code: "ollama-unavailable",
      message: "Ollama stopped before the tutor could respond.",
      technicalMessage: "connection refused",
    });

    render(
      <ConversationHarness
        recorder={recorder}
        respond={respond}
        transcribe={async () => ({ text: "Can we discuss APIs?" })}
      />,
    );

    await recordOneTurn();

    expect(
      await screen.findByText("Ollama stopped before the tutor could respond."),
    ).toBeInTheDocument();
    expect(screen.getByText("Can we discuss APIs?")).toBeInTheDocument();
    expect(screen.getByText("connection refused")).toBeInTheDocument();
    expect(screen.getByRole("button", { name: /hold to talk/i })).toBeEnabled();
  });
});
